# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=b1.7.3
nostalgia_mappings=b1.7.3+build.36
loader_version=0.16.10

# Library Properties
asm_version=9.8

# Mod Properties
mod_version = 0.1.3
maven_group = com.github.Adventurecraft-Awakening
archives_base_name = Macula
